### ISSUE TITLE
[BUG] Nanobody models — EMPTY

### ISSUE THREAD

**Issue by krogala** [brennanaba/ImmuneBuilder#33]
Hi @brennanaba 

I wanted to use NanoBodyBuilder2 on my local server, but it looks like the deep learning models in the GitHub repo are empty. See the location: `ImmuneBuilder/trained_model/nanobody_model_1`

I only noticed this because `torch.load` was throwing an error. Please see below.

```
$ python
Python 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ImmuneBuilder
>>> from ImmuneBuilder import NanoBodyBuilder2
>>> predictor = NanoBodyBuilder2()
ERROR: nanobody_model_1 not downloaded or corrupted.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/CONDA/v23.9.0/envs/immunebuilder/lib/python3.9/site-packages/ImmuneBuilder/NanoBodyBuilder2.py", line 108, in __init__
    raise e
  File "/home/CONDA/v23.9.0/envs/immunebuilder/lib/python3.9/site-packages/ImmuneBuilder/NanoBodyBuilder2.py", line 105, in __init__
    model.load_state_dict(torch.load(weights_path, map_location=torch.device(self.device)))
  File "/home/CONDA/v23.9.0/envs/immunebuilder/lib/python3.9/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/CONDA/v23.9.0/envs/immunebuilder/lib/python3.9/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

And help in getting these models re-uploaded would be great!

Many thanks,

Kacper

**Comment by krogala** [comment]
Never mind!  I found the model files on Zenodo, which I believe is where you uploaded them @brennanaba. The software runs and completes predictions perfectly now.

`https://zenodo.org/records/7258553`

If these were supposed to get downloaded automatically, then that didn't work in my case.
